matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      branches:
        only:
        - master
      script:
        - chmod 777 ./build_release.sh
        - ./build_release.sh
      deploy:
        provider: releases
        api-key: $GITHUB_TOKEN
        file: ./dist.zip
        skip-cleanup: true
        on:
          tags: true

    - language: php
      php:
        - '7.2'
      branches:
        only:
        - master
      before_install:
        - nvm install node
      script:
        - php php/crawl.php
        - php php/format.php
        - npm install
        - export BUILD_GITHUB_PAGES=true
        - npm run build
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
